apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: oy62z27fh-nodejs
  janus-idp.io/tekton: oy62z27fh-nodejs
  backstage.io/kubernetes-id: oy62z27fh-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: oy62z27fh-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
