apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: oy62z27fh-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: oy62z27fh-nodejs 
  name: oy62z27fh-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: oy62z27fh-nodejs 
