apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: oy62z27fh-nodejs-gitops
  description: This is GitOps manifest for oy62z27fh-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=oy62z27fh-nodejs
    backstage.io/kubernetes-id: oy62z27fh-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: oy62z27fh-nodejs
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:oy62z27fh-nodejs
